allowBuilds:
  esbuild: true
  spawn-sync: true
minimumReleaseAgeExclude:
  - '@storybook/addon-a11y@10.6.1'
  - '@storybook/addon-vitest@10.6.1'
  - '@storybook/builder-vite@10.6.1'
  - '@storybook/react-dom-shim@10.6.1'
  - '@storybook/react-vite@10.6.1'
  - '@storybook/react@10.6.1'
  - '@vitest/browser-playwright@5.0.3'
  - '@vitest/browser@5.0.3'
  - '@vitest/mocker@5.0.3'
  - '@vitest/pretty-format@5.0.3'
  - '@vitest/spy@5.0.3'
  - '@vitest/ui@5.0.3'
  - '@vitest/utils@5.0.3'
  - react-virtuoso@4.18.16
  - storybook@10.6.1
  - vitest@5.0.3
onlyBuiltDependencies:
  - esbuild
  - spawn-sync
